included:
  - ABridge
  - ABridgeTests
disabled_rules:
  - opening_brace
  - trailing_comma
excluded:
  - ABridgeCore
  - ABridge/Services/abridge_core.swift
line_length:
  warning: 120
  error: 160
  ignores_urls: true
  ignores_function_declarations: true
type_body_length:
  warning: 300
identifier_name:
  min_length:
    warning: 2
  excluded:
    - id